import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Inter } from "next/font/google";
import { Providers } from "@/components/providers";
import { NavMenu } from "@/components/nav-menu";
import { Footer } from "@/components/footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Album Stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark bg-background text-foreground">
      <body className={inter.className}>
        <Providers>
          <NavMenu />
          <Toaster
            toastOptions={{
              classNames: {
                error: "bg-danger text-danger-900 border-danger-900",
                success: "bg-primary text-primary-900",
                warning: "bg-warning text-warning-900",
                info: "bg-blue-400",
              },
            }}
            position="top-right"
          />
          {children}
          <Footer />
          <Analytics />
          <SpeedInsights />
        </Providers>
      </body>
    </html>
  );
}
